/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jrift_OculusRift */

#ifndef _Included_jrift_OculusRift
#define _Included_jrift_OculusRift
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jrift_OculusRift
 * Method:    initSubsystem
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jrift_OculusRift_initSubsystem
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    pollSubsystem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jrift_OculusRift_pollSubsystem
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    destroySubsystem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jrift_OculusRift_destroySubsystem
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getHResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jrift_OculusRift__1getHResolution
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getVResolution
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jrift_OculusRift__1getVResolution
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getHScreenSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getHScreenSize
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getVScreenSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getVScreenSize
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getVScreenCenter
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getVScreenCenter
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getEyeToScreenDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getEyeToScreenDistance
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getLensSeparationDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getLensSeparationDistance
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getInterpupillaryDistance
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getInterpupillaryDistance
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getDistortionK0
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getDistortionK0
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getDistortionK1
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getDistortionK1
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getDistortionK2
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getDistortionK2
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getDistortionK3
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getDistortionK3
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getYaw
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getYaw
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getPitch
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getPitch
  (JNIEnv *, jobject);

/*
 * Class:     jrift_OculusRift
 * Method:    _getRoll
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_jrift_OculusRift__1getRoll
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
